### ISSUE TITLE
minar memory pool size too high

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/nxpdk5-jn517x-gcc#2] opened 2016-02-25 18:02 UTC
@bangaragirinxp I discovered that the minar memory pool size for the jn517x platform is left to default which is very high. This causes the memory foot print of minar to be very high. [Here](https://github.com/ARMmbed/target-nordic-nrf51822/blob/master/nordic-nrf51822-gcc/target.json) is an example of how you can modify this in the target:
```
    "minar": {
      "initial_event_pool_size": 4,
      "additional_event_pools_size": 4
    },
```

**Comment by bangaragirinxp** [comment] 2016-03-01 03:32
Thanks for finding this issue. The issue is fixed now in github

**Closed by bangaragirinxp** 2016-03-01 03:32 UTC
